import type { StackPreset } from "./stacks"

/**
 * Generate a CLAUDE.md from chain raw JSON outputs + stack preset.
 * No LLM call — pure template derivation.
 */
export function generateClaudeMd(
  rawOutputs: Record<string, string>,
  stack: StackPreset | undefined
): string {
  // Parse what we need from raw JSON
  let projectName = "Untitled Project"
  let doRules: string[] = []
  let dontRules: string[] = []
  let colorPalette: Record<string, string> = {}
  let typographyStyle = ""
  let mood = ""

  // Try AGENT first (runs last, most complete context)
  if (rawOutputs.agent) {
    try {
      const agent = JSON.parse(rawOutputs.agent)
      if (agent.project_name) projectName = agent.project_name
      if (agent.global_rules?.do) doRules = agent.global_rules.do
      if (agent.global_rules?.dont) dontRules = agent.global_rules.dont
    } catch { /* skip */ }
  }

  // Fallback to PRD for project name
  if (projectName === "Untitled Project" && rawOutputs.prd) {
    try {
      const prd = JSON.parse(rawOutputs.prd)
      if (prd.product_name) projectName = prd.product_name
      if (prd.title) projectName = prd.title
    } catch { /* skip */ }
  }

  // DESIGN for visual direction
  if (rawOutputs.design) {
    try {
      const design = JSON.parse(rawOutputs.design)
      const dir = design.design_direction ?? {}
      colorPalette = dir.color_palette ?? {}
      typographyStyle = dir.typography_style ?? ""
      mood = dir.mood ?? ""
    } catch { /* skip */ }
  }

  const lines: string[] = []

  // Header
  lines.push(`# ${projectName}`)
  lines.push("")

  // Stack
  if (stack) {
    lines.push("## Stack")
    lines.push("")
    if (stack.frontend.length > 0) {
      lines.push(`**Frontend:** ${stack.frontend.join(", ")}`)
    }
    if (stack.backend.length > 0) {
      lines.push(`**Backend:** ${stack.backend.join(", ")}`)
    }
    if (stack.database.length > 0) {
      lines.push(`**Database:** ${stack.database.join(", ")}`)
    }
    if (stack.notes && stack.notes.length > 0) {
      lines.push("")
      lines.push("### Notes")
      for (const note of stack.notes) {
        lines.push(`- ${note}`)
      }
    }
    lines.push("")
  }

  // Key Rules
  if (doRules.length > 0) {
    lines.push("## Key Rules")
    lines.push("")
    for (const rule of doRules) {
      lines.push(`- ${rule}`)
    }
    lines.push("")
  }

  // Do NOT
  if (dontRules.length > 0) {
    lines.push("## Do NOT")
    lines.push("")
    for (const rule of dontRules) {
      lines.push(`- ${rule}`)
    }
    lines.push("")
  }

  // Design System
  if (typographyStyle || mood || Object.keys(colorPalette).length > 0) {
    lines.push("## Design System")
    lines.push("")
    if (mood) lines.push(`**Mood:** ${mood}`)
    if (typographyStyle) lines.push(`**Typography:** ${typographyStyle}`)
    if (colorPalette.primary) lines.push(`**Primary Color:** ${colorPalette.primary}`)
    if (colorPalette.secondary) lines.push(`**Secondary Color:** ${colorPalette.secondary}`)
    if (colorPalette.accent) lines.push(`**Accent Color:** ${colorPalette.accent}`)
    if (colorPalette.background) lines.push(`**Background:** ${colorPalette.background}`)
    lines.push("")
  }

  // Documents
  lines.push("## Documents")
  lines.push("")
  lines.push("Read these before starting any work:")
  lines.push("")
  lines.push("- `PRD.md` - Product Requirements")
  lines.push("- `ARD.md` - Architecture & Design")
  lines.push("- `TRD.md` - Technical Requirements")
  lines.push("- `TASKS.md` - Implementation Tasks")
  lines.push("- `AGENT.md` - Agent Instructions")
  lines.push("- `DESIGN.md` - Visual Design Brief")
  lines.push("")

  // Execution Protocol
  lines.push("## Execution Protocol")
  lines.push("")
  lines.push("1. Read ALL documents above before writing any code")
  lines.push("2. Scaffold the project structure based on ARD.md")
  lines.push("3. Implement tasks from TASKS.md one by one")
  lines.push("4. Follow the rules in AGENT.md for every decision")
  lines.push("5. Match the visual direction from DESIGN.md")
  lines.push("")

  return lines.join("\n")
}

/**
 * Generate a build.sh launcher script.
 * Reads all .md files from the folder and feeds them to claude --print.
 */
export function generateBuildSh(projectName: string): string {
  return `#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# ${projectName} - One-Command Builder
# Generated by NODAYSIDLE PRD Compiler
# Usage: cd <project-folder> && bash build.sh
# ============================================================

echo "======================================"
echo "  Building: ${projectName}"
echo "======================================"
echo ""

# Collect all doc files into context
CONTEXT=""
for doc in PRD.md ARD.md TRD.md TASKS.md AGENT.md DESIGN.md; do
  if [ -f "$doc" ]; then
    echo "[+] Loading $doc"
    CONTEXT="$CONTEXT
--- $doc ---
$(cat "$doc")
"
  else
    echo "[ ] Skipping $doc (not found)"
  fi
done

echo ""
echo "Starting build with Claude..."
echo "--------------------------------------"
echo ""

# Feed all docs to Claude with CLAUDE.md as project context
claude --print --max-turns 2 <<PROMPT
You are building a project. Here are all the project documents:

$CONTEXT

Read every document above carefully. Then:
1. Create the full project scaffold (directories + files)
2. Implement every task from TASKS.md
3. Follow all rules from AGENT.md
4. Match the design system from DESIGN.md

Build the complete, working project now.
PROMPT

echo ""
echo "======================================"
echo "  Build complete!"
echo "======================================"
`
}
